/* Generated by           cobc 3.3-dev.0 */
/* Generated from         /tmp/test84.cob */
/* Generated at           Mar 16 2026 17:05:35 */
/* GnuCOBOL build date    Mar 16 2026 06:59:39 */
/* GnuCOBOL package date  Mar 16 2026 01:29:28 UTC */
/* Compile command        /home/utam1/gnucobol/cobc/.libs/cobc -C -Wno-error=unsupported /tmp/test84.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"/tmp/test84.cob"
#define  COB_PACKAGE_VERSION		"3.3-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Mar 16 2026 17:05:35"
#define  COB_MODULE_DATE		20260316
#define  COB_MODULE_TIME		170535

/* Global variables */
#include "test84.c.h"

/* Function prototypes */

COB_EXT_EXPORT int		prog (void);
static int		prog_ (const int);
static void		prog_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'prog' */

/* ENTRY 'prog' */

int
prog ()
{
  return prog_ (0);
}

static int
prog_ (const int entry)
{
  /* Program local variables */
  #include "test84.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 5         : Entry     prog                    : /tmp/test84.cob */
  l_2:;

  /* Line: 5         : STOP RUN           : /tmp/test84.cob */
  cob_stop_run (b_2);

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  prog_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'prog' */

/* Initialize module structure for prog */
static void prog_module_init (cob_module *module__)
{
  module__->module_name = "prog";
  module__->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module__->module_source = COB_SOURCE_FILE;
  module__->gc_version = COB_PACKAGE_VERSION;
  module__->module_entry.funcptr = (void *(*)())prog;
  module__->module_cancel.funcptr = (void *(*)())prog_;
  module__->module_ref_count = NULL;
  module__->module_path = &cob_module_path;
  module__->module_active = 0;
  module__->module_date = COB_MODULE_DATE;
  module__->module_time = COB_MODULE_TIME;
  module__->module_type = 0;
  module__->module_param_cnt = 0;
  module__->ebcdic_sign = 0;
  module__->decimal_point = '.';
  module__->currency_symbol = '$';
  module__->numeric_separator = ',';
  module__->flag_filename_mapping = 1;
  module__->flag_binary_truncate = 1;
  module__->flag_pretty_display = 1;
  module__->flag_host_sign = 0;
  module__->flag_no_phys_canc = 0;
  module__->flag_main = 0;
  module__->flag_fold_call = 0;
  module__->flag_exit_program = 0;
  module__->flag_debug_trace = 0;
  module__->flag_dump_ready = 0;
  module__->xml_mode = 1;
  module__->module_stmt = 0;
  module__->module_sources = NULL;
}

/* End functions */

