/* Generated by           cobc 3.3-dev.0 */
/* Generated from         /tmp/test84.cob */
/* Generated at           Mar 16 2026 17:05:35 */
/* GnuCOBOL build date    Mar 16 2026 06:59:39 */
/* GnuCOBOL package date  Mar 16 2026 01:29:28 UTC */
/* Compile command        /home/utam1/gnucobol/cobc/.libs/cobc -C -Wno-error=unsupported /tmp/test84.cob */

/* Program local variables for 'prog' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */

/* End of local data storage */

