/* Generated by           cobc 3.3-dev.0 */
/* Generated from         /tmp/test84.cob */
/* Generated at           Mar 16 2026 17:05:35 */
/* GnuCOBOL build date    Mar 16 2026 06:59:39 */
/* GnuCOBOL package date  Mar 16 2026 01:29:28 UTC */
/* Compile command        /home/utam1/gnucobol/cobc/.libs/cobc -C -Wno-error=unsupported /tmp/test84.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;
