/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison interface for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

#ifndef YY_YY_PARSER_TAB_H_INCLUDED
# define YY_YY_PARSER_TAB_H_INCLUDED
/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int yydebug;
#endif

/* Token kinds.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    YYEMPTY = -2,
    TOKEN_EOF = 0,                 /* "end of file"  */
    YYerror = 256,                 /* error  */
    YYUNDEF = 257,                 /* "invalid token"  */
    THREEDIMENSIONAL = 258,        /* "3D"  */
    ABSENT = 259,                  /* ABSENT  */
    ACCEPT = 260,                  /* ACCEPT  */
    ACCESS = 261,                  /* ACCESS  */
    ACTIVEX = 262,                 /* "ACTIVE-X"  */
    ACTIVE_CLASS = 263,            /* "ACTIVE-CLASS"  */
    ACTION = 264,                  /* ACTION  */
    ACTUAL = 265,                  /* ACTUAL  */
    ADD = 266,                     /* ADD  */
    ADDRESS = 267,                 /* ADDRESS  */
    ADJUSTABLE_COLUMNS = 268,      /* "ADJUSTABLE-COLUMNS"  */
    ADVANCING = 269,               /* ADVANCING  */
    AFTER = 270,                   /* AFTER  */
    ALIGNED = 271,                 /* ALIGNED  */
    ALIGNMENT = 272,               /* ALIGNMENT  */
    ALL = 273,                     /* ALL  */
    ALLOCATE = 274,                /* ALLOCATE  */
    ALLOWING = 275,                /* ALLOWING  */
    ALPHABET = 276,                /* ALPHABET  */
    ALPHABETIC = 277,              /* ALPHABETIC  */
    ALPHABETIC_LOWER = 278,        /* "ALPHABETIC-LOWER"  */
    ALPHABETIC_UPPER = 279,        /* "ALPHABETIC-UPPER"  */
    ALPHANUMERIC = 280,            /* ALPHANUMERIC  */
    ALPHANUMERIC_EDITED = 281,     /* "ALPHANUMERIC-EDITED"  */
    ALSO = 282,                    /* ALSO  */
    ALTER = 283,                   /* ALTER  */
    ALTERNATE = 284,               /* ALTERNATE  */
    AND = 285,                     /* AND  */
    ANY = 286,                     /* ANY  */
    APPLY = 287,                   /* APPLY  */
    ARE = 288,                     /* ARE  */
    AREA = 289,                    /* AREA  */
    AREAS = 290,                   /* AREAS  */
    ARGUMENT_NUMBER = 291,         /* "ARGUMENT-NUMBER"  */
    ARGUMENT_VALUE = 292,          /* "ARGUMENT-VALUE"  */
    ARITHMETIC = 293,              /* ARITHMETIC  */
    AS = 294,                      /* AS  */
    ASCENDING = 295,               /* ASCENDING  */
    ASCII = 296,                   /* ASCII  */
    ASSIGN = 297,                  /* ASSIGN  */
    AT = 298,                      /* AT  */
    AT_END = 299,                  /* "AT END"  */
    ATTRIBUTE = 300,               /* ATTRIBUTE  */
    ATTRIBUTES = 301,              /* ATTRIBUTES  */
    AUTHOR = 302,                  /* AUTHOR  */
    AUTO = 303,                    /* AUTO  */
    AUTO_DECIMAL = 304,            /* "AUTO-DECIMAL"  */
    AUTO_SPIN = 305,               /* "AUTO-SPIN"  */
    AUTOMATIC = 306,               /* AUTOMATIC  */
    AWAY_FROM_ZERO = 307,          /* "AWAY-FROM-ZERO"  */
    B_AND = 308,                   /* "B-AND"  */
    B_NOT = 309,                   /* "B-NOT"  */
    B_OR = 310,                    /* "B-OR"  */
    B_XOR = 311,                   /* "B-XOR"  */
    B_SHIFT_L = 312,               /* "B-SHIFT-L"  */
    B_SHIFT_R = 313,               /* "B-SHIFT-R"  */
    B_SHIFT_LC = 314,              /* "B-SHIFT-LC"  */
    B_SHIFT_RC = 315,              /* "B-SHIFT-RC"  */
    BACKGROUND_COLOR = 316,        /* "BACKGROUND-COLOR"  */
    BACKGROUND_HIGH = 317,         /* "BACKGROUND-HIGH"  */
    BACKGROUND_LOW = 318,          /* "BACKGROUND-LOW"  */
    BACKGROUND_STANDARD = 319,     /* "BACKGROUND-STANDARD"  */
    BACKWARD = 320,                /* BACKWARD  */
    BAR = 321,                     /* BAR  */
    BASED = 322,                   /* BASED  */
    BEFORE = 323,                  /* BEFORE  */
    BELL = 324,                    /* BELL  */
    BINARY = 325,                  /* BINARY  */
    BINARY_C_LONG = 326,           /* "BINARY-C-LONG"  */
    BINARY_CHAR = 327,             /* "BINARY-CHAR"  */
    BINARY_DOUBLE = 328,           /* "BINARY-DOUBLE"  */
    BINARY_LONG = 329,             /* "BINARY-LONG"  */
    BINARY_SEQUENTIAL = 330,       /* "BINARY-SEQUENTIAL"  */
    BINARY_SHORT = 331,            /* "BINARY-SHORT"  */
    BIT = 332,                     /* BIT  */
    BITMAP = 333,                  /* BITMAP  */
    BITMAP_END = 334,              /* "BITMAP-END"  */
    BITMAP_HANDLE = 335,           /* "BITMAP-HANDLE"  */
    BITMAP_NUMBER = 336,           /* "BITMAP-NUMBER"  */
    BITMAP_START = 337,            /* "BITMAP-START"  */
    BITMAP_TIMER = 338,            /* "BITMAP-TIMER"  */
    BITMAP_TRAILING = 339,         /* "BITMAP-TRAILING"  */
    BITMAP_TRANSPARENT_COLOR = 340, /* "BITMAP-TRANSPARENT-COLOR"  */
    BITMAP_WIDTH = 341,            /* "BITMAP-WIDTH"  */
    BLANK = 342,                   /* BLANK  */
    BLINK = 343,                   /* BLINK  */
    BLOCK = 344,                   /* BLOCK  */
    BOOLEAN = 345,                 /* BOOLEAN  */
    BOTTOM = 346,                  /* BOTTOM  */
    BOX = 347,                     /* BOX  */
    BOXED = 348,                   /* BOXED  */
    BULK_ADDITION = 349,           /* "BULK-ADDITION"  */
    BUSY = 350,                    /* BUSY  */
    BUTTONS = 351,                 /* BUTTONS  */
    BY = 352,                      /* BY  */
    BYTE_LENGTH = 353,             /* "BYTE-LENGTH"  */
    C = 354,                       /* C  */
    CALENDAR_FONT = 355,           /* "CALENDAR-FONT"  */
    CALL = 356,                    /* CALL  */
    CANCEL = 357,                  /* CANCEL  */
    CANCEL_BUTTON = 358,           /* "CANCEL-BUTTON"  */
    CAPACITY = 359,                /* CAPACITY  */
    CARD_PUNCH = 360,              /* "CARD-PUNCH"  */
    CARD_READER = 361,             /* "CARD-READER"  */
    CASSETTE = 362,                /* CASSETTE  */
    CCOL = 363,                    /* CCOL  */
    CD = 364,                      /* CD  */
    CELL = 365,                    /* CELL  */
    CELL_COLOR = 366,              /* "CELL-COLOR"  */
    CELL_DATA = 367,               /* "CELL-DATA"  */
    CELL_FONT = 368,               /* "CELL-FONT"  */
    CELL_PROTECTION = 369,         /* "CELL-PROTECTION"  */
    CENTER = 370,                  /* CENTER  */
    CENTERED = 371,                /* CENTERED  */
    CENTERED_HEADINGS = 372,       /* "CENTERED-HEADINGS"  */
    CENTURY_DATE = 373,            /* "CENTURY-DATE"  */
    CF = 374,                      /* CF  */
    CH = 375,                      /* CH  */
    CHAINING = 376,                /* CHAINING  */
    CHANGED = 377,                 /* CHANGED  */
    CHARACTER = 378,               /* CHARACTER  */
    CHARACTERS = 379,              /* CHARACTERS  */
    CHECK_BOX = 380,               /* "CHECK-BOX"  */
    CLASS = 381,                   /* CLASS  */
    CLASS_ID = 382,                /* CLASS_ID  */
    CLASSIFICATION = 383,          /* CLASSIFICATION  */
    CLASS_NAME = 384,              /* "class-name"  */
    CLEAR_SELECTION = 385,         /* "CLEAR-SELECTION"  */
    CLINE = 386,                   /* CLINE  */
    CLINES = 387,                  /* CLINES  */
    CLOSE = 388,                   /* CLOSE  */
    COBOL = 389,                   /* COBOL  */
    CODE = 390,                    /* CODE  */
    CODE_SET = 391,                /* "CODE-SET"  */
    COLLATING = 392,               /* COLLATING  */
    COL = 393,                     /* COL  */
    COLOR = 394,                   /* COLOR  */
    COLORS = 395,                  /* COLORS  */
    COLS = 396,                    /* COLS  */
    COLUMN = 397,                  /* COLUMN  */
    COLUMN_COLOR = 398,            /* "COLUMN-COLOR"  */
    COLUMN_DIVIDERS = 399,         /* "COLUMN-DIVIDERS"  */
    COLUMN_FONT = 400,             /* "COLUMN-FONT"  */
    COLUMN_HEADINGS = 401,         /* "COLUMN-HEADINGS"  */
    COLUMN_PROTECTION = 402,       /* "COLUMN-PROTECTION"  */
    COLUMNS = 403,                 /* COLUMNS  */
    COMBO_BOX = 404,               /* "COMBO-BOX"  */
    COMMA = 405,                   /* COMMA  */
    COMMAND_LINE = 406,            /* "COMMAND-LINE"  */
    COMMA_DELIM = 407,             /* "comma delimiter"  */
    COMMIT = 408,                  /* COMMIT  */
    COMMON = 409,                  /* COMMON  */
    COMMUNICATION = 410,           /* COMMUNICATION  */
    COMP = 411,                    /* COMP  */
    COMPUTE = 412,                 /* COMPUTE  */
    COMP_0 = 413,                  /* "COMP-0"  */
    COMP_1 = 414,                  /* "COMP-1"  */
    COMP_2 = 415,                  /* "COMP-2"  */
    COMP_3 = 416,                  /* "COMP-3"  */
    COMP_4 = 417,                  /* "COMP-4"  */
    COMP_5 = 418,                  /* "COMP-5"  */
    COMP_6 = 419,                  /* "COMP-6"  */
    COMP_N = 420,                  /* "COMP-N"  */
    COMP_X = 421,                  /* "COMP-X"  */
    CONCATENATE_FUNC = 422,        /* "FUNCTION CONCATENATE"  */
    CONDITION = 423,               /* CONDITION  */
    CONFIGURATION = 424,           /* CONFIGURATION  */
    CONSTANT = 425,                /* CONSTANT  */
    CONTAINS = 426,                /* CONTAINS  */
    CONTENT = 427,                 /* CONTENT  */
    CONTENT_LENGTH_FUNC = 428,     /* "FUNCTION CONTENT-LENGTH"  */
    CONTENT_OF_FUNC = 429,         /* "FUNCTION CONTENT-OF"  */
    CONTINUE = 430,                /* CONTINUE  */
    CONTROL = 431,                 /* CONTROL  */
    CONTROLS = 432,                /* CONTROLS  */
    CONVERSION = 433,              /* CONVERSION  */
    CONVERTING = 434,              /* CONVERTING  */
    COPY = 435,                    /* COPY  */
    COPY_SELECTION = 436,          /* "COPY-SELECTION"  */
    CORE_INDEX = 437,              /* "CORE-INDEX"  */
    CORRESPONDING = 438,           /* CORRESPONDING  */
    COUNT = 439,                   /* COUNT  */
    CRT = 440,                     /* CRT  */
    CRT_UNDER = 441,               /* "CRT-UNDER"  */
    CSIZE = 442,                   /* CSIZE  */
    CURRENCY = 443,                /* CURRENCY  */
    CURRENT_DATE_FUNC = 444,       /* "FUNCTION CURRENT-DATE"  */
    CURSOR = 445,                  /* CURSOR  */
    CURSOR_COL = 446,              /* "CURSOR-COL"  */
    CURSOR_COLOR = 447,            /* "CURSOR-COLOR"  */
    CURSOR_FRAME_WIDTH = 448,      /* "CURSOR-FRAME-WIDTH"  */
    CURSOR_ROW = 449,              /* "CURSOR-ROW"  */
    CURSOR_X = 450,                /* "CURSOR-X"  */
    CURSOR_Y = 451,                /* "CURSOR-Y"  */
    CUSTOM_PRINT_TEMPLATE = 452,   /* "CUSTOM-PRINT-TEMPLATE"  */
    CYCLE = 453,                   /* CYCLE  */
    CYL_INDEX = 454,               /* "CYL-INDEX"  */
    CYL_OVERFLOW = 455,            /* "CYL-OVERFLOW"  */
    DASHED = 456,                  /* DASHED  */
    DATA = 457,                    /* DATA  */
    DATA_COLUMNS = 458,            /* "DATA-COLUMNS"  */
    DATA_POINTER = 459,            /* "DATA-POINTER"  */
    DATA_TYPES = 460,              /* "DATA-TYPES"  */
    DATE = 461,                    /* DATE  */
    DATE_COMPILED = 462,           /* "DATE-COMPILED"  */
    DATE_ENTRY = 463,              /* "DATE-ENTRY"  */
    DATE_MODIFIED = 464,           /* "DATE-MODIFIED"  */
    DATE_WRITTEN = 465,            /* "DATE-WRITTEN"  */
    DAY = 466,                     /* DAY  */
    DAY_OF_WEEK = 467,             /* "DAY-OF-WEEK"  */
    DE = 468,                      /* DE  */
    DEBUGGING = 469,               /* DEBUGGING  */
    DECIMAL_POINT = 470,           /* "DECIMAL-POINT"  */
    DECLARATIVES = 471,            /* DECLARATIVES  */
    DEFAULT = 472,                 /* DEFAULT  */
    DEFAULT_BUTTON = 473,          /* "DEFAULT-BUTTON"  */
    DEFAULT_FONT = 474,            /* "DEFAULT-FONT"  */
    DELETE = 475,                  /* DELETE  */
    DELIMITED = 476,               /* DELIMITED  */
    DELIMITER = 477,               /* DELIMITER  */
    DEPENDING = 478,               /* DEPENDING  */
    DESCENDING = 479,              /* DESCENDING  */
    DESTINATION = 480,             /* DESTINATION  */
    DESTROY = 481,                 /* DESTROY  */
    DETAIL = 482,                  /* DETAIL  */
    DISABLE = 483,                 /* DISABLE  */
    DISC = 484,                    /* DISC  */
    DISK = 485,                    /* DISK  */
    DISP = 486,                    /* DISP  */
    DISPLAY = 487,                 /* DISPLAY  */
    DISPLAY_1 = 488,               /* "DISPLAY-1"  */
    DISPLAY_COLUMNS = 489,         /* "DISPLAY-COLUMNS"  */
    DISPLAY_FORMAT = 490,          /* "DISPLAY-FORMAT"  */
    DISPLAY_OF_FUNC = 491,         /* "FUNCTION DISPLAY-OF"  */
    DIVIDE = 492,                  /* DIVIDE  */
    DIVIDERS = 493,                /* DIVIDERS  */
    DIVIDER_COLOR = 494,           /* "DIVIDER-COLOR"  */
    DIVISION = 495,                /* DIVISION  */
    DOTDASH = 496,                 /* DOTDASH  */
    DOTTED = 497,                  /* DOTTED  */
    DRAG_COLOR = 498,              /* "DRAG-COLOR"  */
    DROP_DOWN = 499,               /* "DROP-DOWN"  */
    DROP_LIST = 500,               /* "DROP-LIST"  */
    DOWN = 501,                    /* DOWN  */
    DUPLICATES = 502,              /* DUPLICATES  */
    DYNAMIC = 503,                 /* DYNAMIC  */
    EBCDIC = 504,                  /* EBCDIC  */
    EC = 505,                      /* EC  */
    ECHO = 506,                    /* ECHO  */
    EGI = 507,                     /* EGI  */
    EIGHTY_EIGHT = 508,            /* "level-number 88"  */
    ENABLE = 509,                  /* ENABLE  */
    ELEMENT = 510,                 /* ELEMENT  */
    ELSE = 511,                    /* ELSE  */
    EMI = 512,                     /* EMI  */
    ENCRYPTION = 513,              /* ENCRYPTION  */
    ENCODING = 514,                /* ENCODING  */
    END = 515,                     /* END  */
    END_ACCEPT = 516,              /* "END-ACCEPT"  */
    END_ADD = 517,                 /* "END-ADD"  */
    END_CALL = 518,                /* "END-CALL"  */
    END_CLASS = 519,               /* "END CLASS"  */
    END_COMPUTE = 520,             /* "END-COMPUTE"  */
    END_COLOR = 521,               /* "END-COLOR"  */
    END_DELETE = 522,              /* "END-DELETE"  */
    END_DISPLAY = 523,             /* "END-DISPLAY"  */
    END_DIVIDE = 524,              /* "END-DIVIDE"  */
    END_EVALUATE = 525,            /* "END-EVALUATE"  */
    END_FUNCTION = 526,            /* "END FUNCTION"  */
    END_IF = 527,                  /* "END-IF"  */
    END_INTERFACE = 528,           /* "END INTERFACE"  */
    END_JSON = 529,                /* "END-JSON"  */
    END_METHOD = 530,              /* "END METHOD"  */
    END_MODIFY = 531,              /* "END-MODIFY"  */
    END_MULTIPLY = 532,            /* "END-MULTIPLY"  */
    END_PERFORM = 533,             /* "END-PERFORM"  */
    END_PROGRAM = 534,             /* "END PROGRAM"  */
    END_READ = 535,                /* "END-READ"  */
    END_RECEIVE = 536,             /* "END-RECEIVE"  */
    END_RETURN = 537,              /* "END-RETURN"  */
    END_REWRITE = 538,             /* "END-REWRITE"  */
    END_SEARCH = 539,              /* "END-SEARCH"  */
    END_SEND = 540,                /* "END-SEND"  */
    END_START = 541,               /* "END-START"  */
    END_STRING = 542,              /* "END-STRING"  */
    END_SUBTRACT = 543,            /* "END-SUBTRACT"  */
    END_UNSTRING = 544,            /* "END-UNSTRING"  */
    END_WRITE = 545,               /* "END-WRITE"  */
    END_XML = 546,                 /* "END-XML"  */
    ENGRAVED = 547,                /* ENGRAVED  */
    ENSURE_VISIBLE = 548,          /* "ENSURE-VISIBLE"  */
    ENTRY = 549,                   /* ENTRY  */
    ENTRY_CONVENTION = 550,        /* "ENTRY-CONVENTION"  */
    ENTRY_FIELD = 551,             /* "ENTRY-FIELD"  */
    ENTRY_REASON = 552,            /* "ENTRY-REASON"  */
    ENVIRONMENT = 553,             /* ENVIRONMENT  */
    ENVIRONMENT_NAME = 554,        /* "ENVIRONMENT-NAME"  */
    ENVIRONMENT_VALUE = 555,       /* "ENVIRONMENT-VALUE"  */
    EOL = 556,                     /* EOL  */
    EOP = 557,                     /* EOP  */
    EOS = 558,                     /* EOS  */
    EQUAL = 559,                   /* EQUAL  */
    ERASE = 560,                   /* ERASE  */
    ERROR = 561,                   /* ERROR  */
    ESCAPE = 562,                  /* ESCAPE  */
    ESCAPE_BUTTON = 563,           /* "ESCAPE-BUTTON"  */
    ESI = 564,                     /* ESI  */
    EVALUATE = 565,                /* EVALUATE  */
    EVENT = 566,                   /* EVENT  */
    EVENT_LIST = 567,              /* "EVENT-LIST"  */
    EVENT_STATUS = 568,            /* "EVENT STATUS"  */
    EVERY = 569,                   /* EVERY  */
    EXAMINE = 570,                 /* EXAMINE  */
    EXCEPTION = 571,               /* EXCEPTION  */
    EXCEPTION_CONDITION = 572,     /* "EXCEPTION CONDITION"  */
    EXCEPTION_VALUE = 573,         /* "EXCEPTION-VALUE"  */
    EXPAND = 574,                  /* EXPAND  */
    EXCLUSIVE = 575,               /* EXCLUSIVE  */
    EXHIBIT = 576,                 /* EXHIBIT  */
    EXIT = 577,                    /* EXIT  */
    EXPONENTIATION = 578,          /* "exponentiation operator"  */
    EXTEND = 579,                  /* EXTEND  */
    EXTENDED_SEARCH = 580,         /* "EXTENDED-SEARCH"  */
    EXTERNAL = 581,                /* EXTERNAL  */
    EXTERNAL_FORM = 582,           /* "EXTERNAL-FORM"  */
    F = 583,                       /* F  */
    FACTORY = 584,                 /* FACTORY  */
    FD = 585,                      /* FD  */
    FH__FCD = 586,                 /* "FH--FCD"  */
    FH__KEYDEF = 587,              /* "FH--KEYDEF"  */
    FILE_CONTROL = 588,            /* "FILE-CONTROL"  */
    FILE_ID = 589,                 /* "FILE-ID"  */
    FILE_LIMIT = 590,              /* "FILE-LIMIT"  */
    FILE_LIMITS = 591,             /* "FILE-LIMITS"  */
    FILE_NAME = 592,               /* "FILE-NAME"  */
    FILE_POS = 593,                /* "FILE-POS"  */
    FILL_COLOR = 594,              /* "FILL-COLOR"  */
    FILL_COLOR2 = 595,             /* "FILL-COLOR2"  */
    FILL_PERCENT = 596,            /* "FILL-PERCENT"  */
    FILLER = 597,                  /* FILLER  */
    FINAL = 598,                   /* FINAL  */
    FINISH_REASON = 599,           /* "FINISH-REASON"  */
    FIRST = 600,                   /* FIRST  */
    FIXED = 601,                   /* FIXED  */
    FIXED_FONT = 602,              /* "FIXED-FONT"  */
    FIXED_WIDTH = 603,             /* "FIXED-WIDTH"  */
    FLAT = 604,                    /* FLAT  */
    FLAT_BUTTONS = 605,            /* "FLAT-BUTTONS"  */
    FLOAT_BINARY_128 = 606,        /* "FLOAT-BINARY-128"  */
    FLOAT_BINARY_32 = 607,         /* "FLOAT-BINARY-32"  */
    FLOAT_BINARY_64 = 608,         /* "FLOAT-BINARY-64"  */
    FLOAT_DECIMAL_16 = 609,        /* "FLOAT-DECIMAL-16"  */
    FLOAT_DECIMAL_34 = 610,        /* "FLOAT-DECIMAL-34"  */
    FLOAT_DECIMAL_7 = 611,         /* "FLOAT-DECIMAL-7"  */
    FLOAT_EXTENDED = 612,          /* "FLOAT-EXTENDED"  */
    FLOAT_LONG = 613,              /* "FLOAT-LONG"  */
    FLOAT_SHORT = 614,             /* "FLOAT-SHORT"  */
    FLOATING = 615,                /* FLOATING  */
    FONT = 616,                    /* FONT  */
    FOOTING = 617,                 /* FOOTING  */
    FOR = 618,                     /* FOR  */
    FOREGROUND_COLOR = 619,        /* "FOREGROUND-COLOR"  */
    FOREVER = 620,                 /* FOREVER  */
    FORMAT = 621,                  /* FORMAT  */
    FORMATTED_DATE_FUNC = 622,     /* "FUNCTION FORMATTED-DATE"  */
    FORMATTED_DATETIME_FUNC = 623, /* "FUNCTION FORMATTED-DATETIME"  */
    FORMATTED_TIME_FUNC = 624,     /* "FUNCTION FORMATTED-TIME"  */
    FRAME = 625,                   /* FRAME  */
    FRAMED = 626,                  /* FRAMED  */
    FREE = 627,                    /* FREE  */
    FROM = 628,                    /* FROM  */
    FROM_CRT = 629,                /* "FROM CRT"  */
    FULL = 630,                    /* FULL  */
    FULL_HEIGHT = 631,             /* "FULL-HEIGHT"  */
    FUNCTION = 632,                /* FUNCTION  */
    FUNCTION_ID = 633,             /* "FUNCTION-ID"  */
    FUNCTION_NAME = 634,           /* "intrinsic function name"  */
    FUNCTION_POINTER = 635,        /* "FUNCTION-POINTER"  */
    GENERATE = 636,                /* GENERATE  */
    GET = 637,                     /* GET  */
    GIVING = 638,                  /* GIVING  */
    GLOBAL = 639,                  /* GLOBAL  */
    GO = 640,                      /* GO  */
    GO_BACK = 641,                 /* "GO-BACK"  */
    GO_FORWARD = 642,              /* "GO-FORWARD"  */
    GO_HOME = 643,                 /* "GO-HOME"  */
    GO_SEARCH = 644,               /* "GO-SEARCH"  */
    GOBACK = 645,                  /* GOBACK  */
    GRAPHICAL = 646,               /* GRAPHICAL  */
    GREATER = 647,                 /* GREATER  */
    GREATER_OR_EQUAL = 648,        /* "GREATER OR EQUAL"  */
    GRID = 649,                    /* GRID  */
    GROUP = 650,                   /* GROUP  */
    GROUP_VALUE = 651,             /* "GROUP-VALUE"  */
    HANDLE = 652,                  /* HANDLE  */
    HAS_CHILDREN = 653,            /* "HAS-CHILDREN"  */
    HEADING = 654,                 /* HEADING  */
    HEADING_COLOR = 655,           /* "HEADING-COLOR"  */
    HEADING_DIVIDER_COLOR = 656,   /* "HEADING-DIVIDER-COLOR"  */
    HEADING_FONT = 657,            /* "HEADING-FONT"  */
    HEAVY = 658,                   /* HEAVY  */
    HEIGHT_IN_CELLS = 659,         /* "HEIGHT-IN-CELLS"  */
    HIDDEN_DATA = 660,             /* "HIDDEN-DATA"  */
    HIGHLIGHT = 661,               /* HIGHLIGHT  */
    HIGH_COLOR = 662,              /* "HIGH-COLOR"  */
    HIGH_VALUE = 663,              /* "HIGH-VALUE"  */
    HOT_TRACK = 664,               /* "HOT-TRACK"  */
    HSCROLL = 665,                 /* HSCROLL  */
    HSCROLL_POS = 666,             /* "HSCROLL-POS"  */
    ICON = 667,                    /* ICON  */
    ID = 668,                      /* ID  */
    IDENTIFIED = 669,              /* IDENTIFIED  */
    IDENTIFICATION = 670,          /* IDENTIFICATION  */
    IF = 671,                      /* IF  */
    IGNORE = 672,                  /* IGNORE  */
    IGNORING = 673,                /* IGNORING  */
    IN = 674,                      /* IN  */
    INDEPENDENT = 675,             /* INDEPENDENT  */
    INDEX = 676,                   /* INDEX  */
    INDEXED = 677,                 /* INDEXED  */
    INDICATE = 678,                /* INDICATE  */
    INHERITS = 679,                /* INHERITS  */
    INITIALIZE = 680,              /* INITIALIZE  */
    INITIALIZED = 681,             /* INITIALIZED  */
    INITIATE = 682,                /* INITIATE  */
    INTERFACE = 683,               /* INTERFACE  */
    INTERFACE_ID = 684,            /* INTERFACE_ID  */
    IMPLEMENTS = 685,              /* IMPLEMENTS  */
    INPUT = 686,                   /* INPUT  */
    INPUT_OUTPUT = 687,            /* "INPUT-OUTPUT"  */
    INQUIRE = 688,                 /* INQUIRE  */
    INSERTION_INDEX = 689,         /* "INSERTION-INDEX"  */
    INSERT_ROWS = 690,             /* "INSERT-ROWS"  */
    INSPECT = 691,                 /* INSPECT  */
    INSTALLATION = 692,            /* INSTALLATION  */
    INTERMEDIATE = 693,            /* INTERMEDIATE  */
    INTO = 694,                    /* INTO  */
    INTRINSIC = 695,               /* INTRINSIC  */
    INVALID = 696,                 /* INVALID  */
    INVALID_KEY = 697,             /* "INVALID KEY"  */
    INVOKE = 698,                  /* INVOKE  */
    IS = 699,                      /* IS  */
    IS_FINAL = 700,                /* "IS FINAL"  */
    ITEM = 701,                    /* ITEM  */
    ITEM_TEXT = 702,               /* "ITEM-TEXT"  */
    ITEM_TO_ADD = 703,             /* "ITEM-TO_ADD"  */
    ITEM_TO_DELETE = 704,          /* "ITEM-TO_DELETE"  */
    ITEM_TO_EMPTY = 705,           /* "ITEM-TO_EMPTY"  */
    ITEM_VALUE = 706,              /* "ITEM-VALUE"  */
    I_O = 707,                     /* "I-O"  */
    I_O_CONTROL = 708,             /* "I-O-CONTROL"  */
    JSON = 709,                    /* JSON  */
    JUSTIFIED = 710,               /* JUSTIFIED  */
    KEPT = 711,                    /* KEPT  */
    KEY = 712,                     /* KEY  */
    KEYBOARD = 713,                /* KEYBOARD  */
    LABEL = 714,                   /* LABEL  */
    LABEL_OFFSET = 715,            /* "LABEL-OFFSET"  */
    LARGE_FONT = 716,              /* "LARGE-FONT"  */
    LARGE_OFFSET = 717,            /* "LARGE-OFFSET"  */
    LAST = 718,                    /* LAST  */
    LAST_ROW = 719,                /* "LAST-ROW"  */
    LAYOUT_DATA = 720,             /* "LAYOUT-DATA"  */
    LAYOUT_MANAGER = 721,          /* "LAYOUT-MANAGER"  */
    LEADING = 722,                 /* LEADING  */
    LEADING_SHIFT = 723,           /* "LEADING-SHIFT"  */
    LEAVE = 724,                   /* LEAVE  */
    LEFT = 725,                    /* LEFT  */
    LEFTLINE = 726,                /* LEFTLINE  */
    LEFT_TEXT = 727,               /* "LEFT-TEXT"  */
    LENGTH = 728,                  /* LENGTH  */
    LENGTH_OF = 729,               /* "LENGTH OF"  */
    LENGTH_FUNC = 730,             /* "FUNCTION LENGTH/BYTE-LENGTH"  */
    LESS = 731,                    /* LESS  */
    LESS_OR_EQUAL = 732,           /* "LESS OR EQUAL"  */
    LEVEL_NUMBER = 733,            /* "level-number"  */
    LIKE = 734,                    /* LIKE  */
    LIMIT = 735,                   /* LIMIT  */
    LIMITS = 736,                  /* LIMITS  */
    LINAGE = 737,                  /* LINAGE  */
    LINAGE_COUNTER = 738,          /* "LINAGE-COUNTER"  */
    LINE = 739,                    /* LINE  */
    LINE_COUNTER = 740,            /* "LINE-COUNTER"  */
    LINE_LIMIT = 741,              /* "LINE LIMIT"  */
    LINE_SEQUENTIAL = 742,         /* "LINE-SEQUENTIAL"  */
    LINES = 743,                   /* LINES  */
    LINES_AT_ROOT = 744,           /* "LINES-AT-ROOT"  */
    LINKAGE = 745,                 /* LINKAGE  */
    LIST_BOX = 746,                /* "LIST-BOX"  */
    LITERAL = 747,                 /* "Literal"  */
    LM_RESIZE = 748,               /* "LM-RESIZE"  */
    LOC = 749,                     /* LOC  */
    LOCALE = 750,                  /* LOCALE  */
    LOCALE_DATE_FUNC = 751,        /* "FUNCTION LOCALE-DATE"  */
    LOCALE_TIME_FUNC = 752,        /* "FUNCTION LOCALE-TIME"  */
    LOCALE_TIME_FROM_FUNC = 753,   /* "FUNCTION LOCALE-TIME-FROM-SECONDS"  */
    LOCAL_STORAGE = 754,           /* "LOCAL-STORAGE"  */
    LOCK = 755,                    /* LOCK  */
    LOCK_HOLDING = 756,            /* "LOCK-HOLDING"  */
    LONG_DATE = 757,               /* "LONG-DATE"  */
    LOWER = 758,                   /* LOWER  */
    LOWERED = 759,                 /* LOWERED  */
    LOWER_CASE_FUNC = 760,         /* "FUNCTION LOWER-CASE"  */
    LOWLIGHT = 761,                /* LOWLIGHT  */
    LOW_COLOR = 762,               /* "LOW-COLOR"  */
    LOW_VALUE = 763,               /* "LOW-VALUE"  */
    MAGNETIC_TAPE = 764,           /* "MAGNETIC-TAPE"  */
    MANUAL = 765,                  /* MANUAL  */
    MASS_UPDATE = 766,             /* "MASS-UPDATE"  */
    MASTER_INDEX = 767,            /* "MASTER-INDEX"  */
    MAX_LINES = 768,               /* "MAX-LINES"  */
    MAX_PROGRESS = 769,            /* "MAX-PROGRESS"  */
    MAX_TEXT = 770,                /* "MAX-TEXT"  */
    MAX_VAL = 771,                 /* "MAX-VAL"  */
    MEMORY = 772,                  /* MEMORY  */
    MEDIUM_FONT = 773,             /* "MEDIUM-FONT"  */
    MENU = 774,                    /* MENU  */
    MERGE = 775,                   /* MERGE  */
    MESSAGE = 776,                 /* MESSAGE  */
    METHOD = 777,                  /* METHOD  */
    METHOD_ID = 778,               /* METHOD_ID  */
    MICROSECOND_TIME = 779,        /* "MICROSECOND-TIME"  */
    MINUS = 780,                   /* MINUS  */
    MIN_VAL = 781,                 /* "MIN-VAL"  */
    MNEMONIC_NAME = 782,           /* "Mnemonic name"  */
    MODE = 783,                    /* MODE  */
    MODIFY = 784,                  /* MODIFY  */
    MODULES = 785,                 /* MODULES  */
    MOVE = 786,                    /* MOVE  */
    MULTILINE = 787,               /* MULTILINE  */
    MULTIPLE = 788,                /* MULTIPLE  */
    MULTIPLY = 789,                /* MULTIPLY  */
    NAME = 790,                    /* NAME  */
    NAMED = 791,                   /* NAMED  */
    NAMESPACE = 792,               /* NAMESPACE  */
    NAMESPACE_PREFIX = 793,        /* "NAMESPACE-PREFIX"  */
    NATIONAL = 794,                /* NATIONAL  */
    NATIONAL_EDITED = 795,         /* "NATIONAL-EDITED"  */
    NATIONAL_OF_FUNC = 796,        /* "FUNCTION NATIONAL-OF"  */
    NATIVE = 797,                  /* NATIVE  */
    NAVIGATE_URL = 798,            /* "NAVIGATE-URL"  */
    NEAREST_AWAY_FROM_ZERO = 799,  /* "NEAREST-AWAY-FROM-ZERO"  */
    NEAREST_EVEN = 800,            /* "NEAREST-EVEN"  */
    NEAREST_TOWARD_ZERO = 801,     /* "NEAREST-TOWARD-ZERO"  */
    NEGATIVE = 802,                /* NEGATIVE  */
    NESTED = 803,                  /* NESTED  */
    NEW = 804,                     /* NEW  */
    NEXT = 805,                    /* NEXT  */
    NEXT_ITEM = 806,               /* "NEXT-ITEM"  */
    NEXT_GROUP = 807,              /* "NEXT GROUP"  */
    NEXT_PAGE = 808,               /* "NEXT PAGE"  */
    NO = 809,                      /* NO  */
    NO_ADVANCING = 810,            /* "NO ADVANCING"  */
    NO_AUTOSEL = 811,              /* "NO-AUTOSEL"  */
    NO_AUTO_DEFAULT = 812,         /* "NO-AUTO-DEFAULT"  */
    NO_BOX = 813,                  /* "NO-BOX"  */
    NO_DATA = 814,                 /* "NO DATA"  */
    NO_DIVIDERS = 815,             /* "NO-DIVIDERS"  */
    NO_ECHO = 816,                 /* "NO-ECHO"  */
    NO_F4 = 817,                   /* "NO-F4"  */
    NO_FOCUS = 818,                /* "NO-FOCUS"  */
    NO_GROUP_TAB = 819,            /* "NO-GROUP-TAB"  */
    NO_KEY_LETTER = 820,           /* "NO-KEY-LETTER"  */
    NO_SEARCH = 821,               /* "NO-SEARCH"  */
    NO_UPDOWN = 822,               /* "NO-UPDOWN"  */
    NOMINAL = 823,                 /* NOMINAL  */
    NONE = 824,                    /* NONE  */
    NONNUMERIC = 825,              /* NONNUMERIC  */
    NORMAL = 826,                  /* NORMAL  */
    NOT = 827,                     /* NOT  */
    NOTAB = 828,                   /* NOTAB  */
    NOTHING = 829,                 /* NOTHING  */
    NOTIFY = 830,                  /* NOTIFY  */
    NOTIFY_CHANGE = 831,           /* "NOTIFY-CHANGE"  */
    NOTIFY_DBLCLICK = 832,         /* "NOTIFY-DBLCLICK"  */
    NOTIFY_SELCHANGE = 833,        /* "NOTIFY-SELCHANGE"  */
    NOT_AT_END = 834,              /* "NOT AT END"  */
    NOT_EOP = 835,                 /* "NOT AT EOP"  */
    NOT_ON_ESCAPE = 836,           /* "NOT ON ESCAPE"  */
    NOT_EQUAL = 837,               /* "NOT EQUAL"  */
    NOT_ON_EXCEPTION = 838,        /* "NOT ON EXCEPTION"  */
    NOT_INVALID_KEY = 839,         /* "NOT INVALID KEY"  */
    NOT_ON_OVERFLOW = 840,         /* "NOT ON OVERFLOW"  */
    NOT_SIZE_ERROR = 841,          /* "NOT SIZE ERROR"  */
    NUM_COL_HEADINGS = 842,        /* "NUM-COL-HEADINGS"  */
    NUM_ROWS = 843,                /* "NUM-ROWS"  */
    NUMBER = 844,                  /* NUMBER  */
    NUMBERS = 845,                 /* NUMBERS  */
    NUMERIC = 846,                 /* NUMERIC  */
    NUMERIC_EDITED = 847,          /* "NUMERIC-EDITED"  */
    NUMVALC_FUNC = 848,            /* "FUNCTION NUMVAL-C"  */
    OBJECT = 849,                  /* OBJECT  */
    OBJECT_COMPUTER = 850,         /* "OBJECT-COMPUTER"  */
    OCCURS = 851,                  /* OCCURS  */
    OF = 852,                      /* OF  */
    OFF = 853,                     /* OFF  */
    OK_BUTTON = 854,               /* "OK-BUTTON"  */
    OMITTED = 855,                 /* OMITTED  */
    ON = 856,                      /* ON  */
    ONLY = 857,                    /* ONLY  */
    ON_ESCAPE = 858,               /* "ON ESCAPE"  */
    ON_EXCEPTION = 859,            /* "ON EXCEPTION"  */
    OPEN = 860,                    /* OPEN  */
    OPTIONAL = 861,                /* OPTIONAL  */
    OPTIONS = 862,                 /* OPTIONS  */
    OR = 863,                      /* OR  */
    ORDER = 864,                   /* ORDER  */
    ORGANIZATION = 865,            /* ORGANIZATION  */
    OTHER = 866,                   /* OTHER  */
    OTHERS = 867,                  /* OTHERS  */
    OUTPUT = 868,                  /* OUTPUT  */
    OVERLAP_LEFT = 869,            /* "OVERLAP-LEFT"  */
    OVERLAP_TOP = 870,             /* "OVERLAP-TOP"  */
    OVERLINE = 871,                /* OVERLINE  */
    OVERRIDE = 872,                /* OVERRIDE  */
    PACKED_DECIMAL = 873,          /* "PACKED-DECIMAL"  */
    PADDING = 874,                 /* PADDING  */
    PASCAL = 875,                  /* PASCAL  */
    PAGE = 876,                    /* PAGE  */
    PAGE_COUNTER = 877,            /* "PAGE-COUNTER"  */
    PAGE_SETUP = 878,              /* "PAGE-SETUP"  */
    PAGED = 879,                   /* PAGED  */
    PARAGRAPH = 880,               /* PARAGRAPH  */
    PARENT = 881,                  /* PARENT  */
    PARSE = 882,                   /* PARSE  */
    PASSWORD = 883,                /* PASSWORD  */
    PERFORM = 884,                 /* PERFORM  */
    PERMANENT = 885,               /* PERMANENT  */
    PH = 886,                      /* PH  */
    PF = 887,                      /* PF  */
    PHYSICAL = 888,                /* PHYSICAL  */
    PICTURE = 889,                 /* PICTURE  */
    PICTURE_SYMBOL = 890,          /* "PICTURE SYMBOL"  */
    PIXEL = 891,                   /* PIXEL  */
    PLACEMENT = 892,               /* PLACEMENT  */
    PLUS = 893,                    /* PLUS  */
    POINTER = 894,                 /* POINTER  */
    POP_UP = 895,                  /* "POP-UP"  */
    POS = 896,                     /* POS  */
    POSITION = 897,                /* POSITION  */
    POSITION_SHIFT = 898,          /* "POSITION-SHIFT"  */
    POSITIVE = 899,                /* POSITIVE  */
    PRESENT = 900,                 /* PRESENT  */
    PREVIOUS = 901,                /* PREVIOUS  */
    PRINT = 902,                   /* PRINT  */
    PRINT_CONTROL = 903,           /* "PRINT-CONTROL"  */
    PRINT_NO_PROMPT = 904,         /* "PRINT-NO-PROMPT"  */
    PRINT_PREVIEW = 905,           /* "PRINT-PREVIEW"  */
    PRINTER = 906,                 /* PRINTER  */
    PRINTER_1 = 907,               /* "PRINTER-1"  */
    PRINTING = 908,                /* PRINTING  */
    PRIORITY = 909,                /* PRIORITY  */
    PROCEDURE = 910,               /* PROCEDURE  */
    PROCEDURES = 911,              /* PROCEDURES  */
    PROCEED = 912,                 /* PROCEED  */
    PROCESSING = 913,              /* PROCESSING  */
    PROGRAM = 914,                 /* PROGRAM  */
    PROGRAM_ID = 915,              /* "PROGRAM-ID"  */
    PROGRAM_NAME = 916,            /* "program name"  */
    PROGRAM_POINTER = 917,         /* "PROGRAM-POINTER"  */
    PROGRESS = 918,                /* PROGRESS  */
    PROHIBITED = 919,              /* PROHIBITED  */
    PROMPT = 920,                  /* PROMPT  */
    PROPERTIES = 921,              /* PROPERTIES  */
    PROPERTY = 922,                /* PROPERTY  */
    PROTECTED = 923,               /* PROTECTED  */
    PROTOTYPE = 924,               /* PROTOTYPE  */
    PURGE = 925,                   /* PURGE  */
    PUSH_BUTTON = 926,             /* "PUSH-BUTTON"  */
    QUERY_INDEX = 927,             /* "QUERY-INDEX"  */
    QUEUE = 928,                   /* QUEUE  */
    QUOTE = 929,                   /* QUOTE  */
    RADIO_BUTTON = 930,            /* "RADIO-BUTTON"  */
    RAISE = 931,                   /* RAISE  */
    RAISED = 932,                  /* RAISED  */
    RAISING = 933,                 /* RAISING  */
    RANDOM = 934,                  /* RANDOM  */
    RD = 935,                      /* RD  */
    READ = 936,                    /* READ  */
    READERS = 937,                 /* READERS  */
    READ_ONLY = 938,               /* "READ-ONLY"  */
    READY_TRACE = 939,             /* "READY TRACE"  */
    RECEIVE = 940,                 /* RECEIVE  */
    RECEIVED = 941,                /* RECEIVED  */
    RECORD = 942,                  /* RECORD  */
    RECORD_DATA = 943,             /* "RECORD-DATA"  */
    RECORD_OVERFLOW = 944,         /* "RECORD-OVERFLOW"  */
    RECORD_TO_ADD = 945,           /* "RECORD-TO-ADD"  */
    RECORD_TO_DELETE = 946,        /* "RECORD-TO-DELETE"  */
    RECORDING = 947,               /* RECORDING  */
    RECORDS = 948,                 /* RECORDS  */
    RECURSIVE = 949,               /* RECURSIVE  */
    REDEFINES = 950,               /* REDEFINES  */
    REEL = 951,                    /* REEL  */
    REFERENCE = 952,               /* REFERENCE  */
    REFERENCES = 953,              /* REFERENCES  */
    REFRESH = 954,                 /* REFRESH  */
    REGION_COLOR = 955,            /* "REGION-COLOR"  */
    RELATION = 956,                /* RELATION  */
    RELATIVE = 957,                /* RELATIVE  */
    RELEASE = 958,                 /* RELEASE  */
    REMAINDER = 959,               /* REMAINDER  */
    REMARKS = 960,                 /* REMARKS  */
    REMOVAL = 961,                 /* REMOVAL  */
    RENAMES = 962,                 /* RENAMES  */
    REORG_CRITERIA = 963,          /* "REORG-CRITERIA"  */
    REPEATED = 964,                /* REPEATED  */
    REPLACE = 965,                 /* REPLACE  */
    REPLACING = 966,               /* REPLACING  */
    REPORT = 967,                  /* REPORT  */
    REPORTING = 968,               /* REPORTING  */
    REPORTS = 969,                 /* REPORTS  */
    REPOSITORY = 970,              /* REPOSITORY  */
    REQUIRED = 971,                /* REQUIRED  */
    REREAD = 972,                  /* REREAD  */
    RERUN = 973,                   /* RERUN  */
    RESERVE = 974,                 /* RESERVE  */
    RESET = 975,                   /* RESET  */
    RESET_TRACE = 976,             /* "RESET TRACE"  */
    RESET_GRID = 977,              /* "RESET-GRID"  */
    RESET_LIST = 978,              /* "RESET-LIST"  */
    RESET_TABS = 979,              /* "RESET-TABS"  */
    RETRY = 980,                   /* RETRY  */
    RETURN = 981,                  /* RETURN  */
    RETURNING = 982,               /* RETURNING  */
    REVERSE = 983,                 /* REVERSE  */
    REVERSE_FUNC = 984,            /* "FUNCTION REVERSE"  */
    REVERSE_VIDEO = 985,           /* "REVERSE-VIDEO"  */
    REVERSED = 986,                /* REVERSED  */
    REWIND = 987,                  /* REWIND  */
    REWRITE = 988,                 /* REWRITE  */
    RF = 989,                      /* RF  */
    RH = 990,                      /* RH  */
    RIGHT = 991,                   /* RIGHT  */
    RIGHT_ALIGN = 992,             /* "RIGHT-ALIGN"  */
    RIGHTLINE = 993,               /* RIGHTLINE  */
    RIMMED = 994,                  /* RIMMED  */
    ROLLBACK = 995,                /* ROLLBACK  */
    ROUNDED = 996,                 /* ROUNDED  */
    ROUNDING = 997,                /* ROUNDING  */
    ROW_COLOR = 998,               /* "ROW-COLOR"  */
    ROW_COLOR_PATTERN = 999,       /* "ROW-COLOR-PATTERN"  */
    ROW_DIVIDERS = 1000,           /* "ROW-DIVIDERS"  */
    ROW_FONT = 1001,               /* "ROW-FONT"  */
    ROW_HEADINGS = 1002,           /* "ROW-HEADINGS"  */
    ROW_PROTECTION = 1003,         /* "ROW-PROTECTION"  */
    RUN = 1004,                    /* RUN  */
    S = 1005,                      /* S  */
    SAME = 1006,                   /* SAME  */
    SAVE_AS = 1007,                /* "SAVE-AS"  */
    SAVE_AS_NO_PROMPT = 1008,      /* "SAVE-AS-NO-PROMPT"  */
    SCREEN = 1009,                 /* SCREEN  */
    SCREEN_CONTROL = 1010,         /* "SCREEN CONTROL"  */
    SCROLL = 1011,                 /* SCROLL  */
    SCROLL_BAR = 1012,             /* "SCROLL-BAR"  */
    SD = 1013,                     /* SD  */
    SEARCH = 1014,                 /* SEARCH  */
    SEARCH_OPTIONS = 1015,         /* "SEARCH-OPTIONS"  */
    SEARCH_TEXT = 1016,            /* "SEARCH-TEXT"  */
    SECONDS = 1017,                /* SECONDS  */
    SECTION = 1018,                /* SECTION  */
    SECURE = 1019,                 /* SECURE  */
    SECURITY = 1020,               /* SECURITY  */
    SEGMENT = 1021,                /* SEGMENT  */
    SEGMENT_LIMIT = 1022,          /* "SEGMENT-LIMIT"  */
    SELECT = 1023,                 /* SELECT  */
    SELECTION_INDEX = 1024,        /* "SELECTION-INDEX"  */
    SELECTION_TEXT = 1025,         /* "SELECTION-TEXT"  */
    SELECT_ALL = 1026,             /* "SELECTION-ALL"  */
    SELF_ACT = 1027,               /* "SELF-ACT"  */
    SEMI_COLON = 1028,             /* "semi-colon"  */
    SEND = 1029,                   /* SEND  */
    SENTENCE = 1030,               /* SENTENCE  */
    SEPARATE = 1031,               /* SEPARATE  */
    SEPARATION = 1032,             /* SEPARATION  */
    SEQUENCE = 1033,               /* SEQUENCE  */
    SEQUENTIAL = 1034,             /* SEQUENTIAL  */
    SET = 1035,                    /* SET  */
    SEVENTY_EIGHT = 1036,          /* "level-number 78"  */
    SHADING = 1037,                /* SHADING  */
    SHADOW = 1038,                 /* SHADOW  */
    SHARING = 1039,                /* SHARING  */
    SHORT_DATE = 1040,             /* "SHORT-DATE"  */
    SHOW_LINES = 1041,             /* "SHOW-LINES"  */
    SHOW_NONE = 1042,              /* "SHOW-NONE"  */
    SHOW_SEL_ALWAYS = 1043,        /* "SHOW-SEL-ALWAYS"  */
    SIGN = 1044,                   /* SIGN  */
    SIGNED = 1045,                 /* SIGNED  */
    SIGNED_INT = 1046,             /* "SIGNED-INT"  */
    SIGNED_LONG = 1047,            /* "SIGNED-LONG"  */
    SIGNED_SHORT = 1048,           /* "SIGNED-SHORT"  */
    SIXTY_SIX = 1049,              /* "level-number 66"  */
    SIZE = 1050,                   /* SIZE  */
    SIZE_ERROR = 1051,             /* "SIZE ERROR"  */
    SMALL_FONT = 1052,             /* "SMALL-FONT"  */
    SORT = 1053,                   /* SORT  */
    SORT_MERGE = 1054,             /* "SORT-MERGE"  */
    SORT_ORDER = 1055,             /* "SORT-ORDER"  */
    SOURCE = 1056,                 /* SOURCE  */
    SOURCE_COMPUTER = 1057,        /* "SOURCE-COMPUTER"  */
    SPACE = 1058,                  /* SPACE  */
    SPECIAL_NAMES = 1059,          /* "SPECIAL-NAMES"  */
    SPINNER = 1060,                /* SPINNER  */
    SQUARE = 1061,                 /* SQUARE  */
    STANDARD = 1062,               /* STANDARD  */
    STANDARD_1 = 1063,             /* "STANDARD-1"  */
    STANDARD_2 = 1064,             /* "STANDARD-2"  */
    STANDARD_BINARY = 1065,        /* "STANDARD-BINARY"  */
    STANDARD_DECIMAL = 1066,       /* "STANDARD-DECIMAL"  */
    START = 1067,                  /* START  */
    START_X = 1068,                /* "START-X"  */
    START_Y = 1069,                /* "START-Y"  */
    STATIC = 1070,                 /* STATIC  */
    STATIC_LIST = 1071,            /* "STATIC-LIST"  */
    STATUS = 1072,                 /* STATUS  */
    STATUS_BAR = 1073,             /* "STATUS-BAR"  */
    STATUS_TEXT = 1074,            /* "STATUS-TEXT"  */
    STDCALL = 1075,                /* STDCALL  */
    STEP = 1076,                   /* STEP  */
    STOP = 1077,                   /* STOP  */
    STRING = 1078,                 /* STRING  */
    STRONG = 1079,                 /* STRONG  */
    STYLE = 1080,                  /* STYLE  */
    SUB_QUEUE_1 = 1081,            /* "SUB-QUEUE-1"  */
    SUB_QUEUE_2 = 1082,            /* "SUB-QUEUE-2"  */
    SUB_QUEUE_3 = 1083,            /* "SUB-QUEUE-3"  */
    SUBSTITUTE_FUNC = 1084,        /* "FUNCTION SUBSTITUTE"  */
    SUBSTITUTE_CASE_FUNC = 1085,   /* "FUNCTION SUBSTITUTE-CASE"  */
    SUBTRACT = 1086,               /* SUBTRACT  */
    SUBWINDOW = 1087,              /* SUBWINDOW  */
    SUM = 1088,                    /* SUM  */
    SUPPRESS = 1089,               /* SUPPRESS  */
    SUPPRESS_XML = 1090,           /* "SUPPRESS"  */
    SYMBOLIC = 1091,               /* SYMBOLIC  */
    SYNCHRONIZED = 1092,           /* SYNCHRONIZED  */
    SYSTEM_DEFAULT = 1093,         /* "SYSTEM-DEFAULT"  */
    SYSTEM_INFO = 1094,            /* "SYSTEM-INFO"  */
    SYSTEM_OFFSET = 1095,          /* "SYSTEM-OFFSET"  */
    TAB = 1096,                    /* TAB  */
    TAB_TO_ADD = 1097,             /* "TAB-TO-ADD"  */
    TAB_TO_DELETE = 1098,          /* "TAB-TO-DELETE"  */
    TABLE = 1099,                  /* TABLE  */
    TALLYING = 1100,               /* TALLYING  */
    TEMPORARY = 1101,              /* TEMPORARY  */
    TAPE = 1102,                   /* TAPE  */
    TERMINAL = 1103,               /* TERMINAL  */
    TERMINATE = 1104,              /* TERMINATE  */
    TERMINAL_INFO = 1105,          /* "TERMINAL-INFO"  */
    TERMINATION_VALUE = 1106,      /* "TERMINATION-VALUE"  */
    TEST = 1107,                   /* TEST  */
    TEXT = 1108,                   /* TEXT  */
    THAN = 1109,                   /* THAN  */
    THEN = 1110,                   /* THEN  */
    THREAD = 1111,                 /* THREAD  */
    THREADS = 1112,                /* THREADS  */
    THRU = 1113,                   /* THRU  */
    THUMB_POSITION = 1114,         /* "THUMB-POSITION"  */
    TILED_HEADINGS = 1115,         /* "TILED-HEADINGS"  */
    TIME = 1116,                   /* TIME  */
    TIME_OUT = 1117,               /* "TIME-OUT"  */
    TIMES = 1118,                  /* TIMES  */
    TITLE = 1119,                  /* TITLE  */
    TITLE_POSITION = 1120,         /* "TITLE-POSITION"  */
    TO = 1121,                     /* TO  */
    TOK_AMPER = 1122,              /* "&"  */
    TOK_CLOSE_PAREN = 1123,        /* ")"  */
    TOK_COLON = 1124,              /* ":"  */
    TOK_DIV = 1125,                /* "/"  */
    TOK_DOT = 1126,                /* "."  */
    TOK_EQUAL = 1127,              /* "="  */
    TOK_EXTERN = 1128,             /* "EXTERN"  */
    TOK_FALSE = 1129,              /* "FALSE"  */
    TOK_FILE = 1130,               /* "FILE"  */
    TOK_GREATER = 1131,            /* ">"  */
    TOK_INITIAL = 1132,            /* "INITIAL"  */
    TOK_LESS = 1133,               /* "<"  */
    TOK_MINUS = 1134,              /* "-"  */
    TOK_MUL = 1135,                /* "*"  */
    TOK_NULL = 1136,               /* "NULL"  */
    TOK_OVERFLOW = 1137,           /* "OVERFLOW"  */
    TOK_OPEN_PAREN = 1138,         /* "("  */
    TOK_PLUS = 1139,               /* "+"  */
    TOK_TRUE = 1140,               /* "TRUE"  */
    TOP = 1141,                    /* TOP  */
    TOWARD_GREATER = 1142,         /* "TOWARD-GREATER"  */
    TOWARD_LESSER = 1143,          /* "TOWARD-LESSER"  */
    TRACK = 1144,                  /* TRACK  */
    TRACKS = 1145,                 /* TRACKS  */
    TRACK_AREA = 1146,             /* "TRACK-AREA"  */
    TRACK_LIMIT = 1147,            /* "TRACK-LIMIT"  */
    TRADITIONAL_FONT = 1148,       /* "TRADITIONAL-FONT"  */
    TRAILING = 1149,               /* TRAILING  */
    TRAILING_SHIFT = 1150,         /* "TRAILING-SHIFT"  */
    TRANSFORM = 1151,              /* TRANSFORM  */
    TRANSPARENT = 1152,            /* TRANSPARENT  */
    TREE_VIEW = 1153,              /* "TREE-VIEW"  */
    TRIM_FUNC = 1154,              /* "FUNCTION TRIM"  */
    TRUNCATION = 1155,             /* TRUNCATION  */
    TYPE = 1156,                   /* TYPE  */
    TYPEDEF = 1157,                /* TYPEDEF  */
    U = 1158,                      /* U  */
    UCS_4 = 1159,                  /* "UCS-4"  */
    UNBOUNDED = 1160,              /* UNBOUNDED  */
    UNDERLINE = 1161,              /* UNDERLINE  */
    UNFRAMED = 1162,               /* UNFRAMED  */
    UNIT = 1163,                   /* UNIT  */
    UNLOCK = 1164,                 /* UNLOCK  */
    UNSIGNED = 1165,               /* UNSIGNED  */
    UNSIGNED_INT = 1166,           /* "UNSIGNED-INT"  */
    UNSIGNED_LONG = 1167,          /* "UNSIGNED-LONG"  */
    UNSIGNED_SHORT = 1168,         /* "UNSIGNED-SHORT"  */
    UNSORTED = 1169,               /* UNSORTED  */
    UNSTRING = 1170,               /* UNSTRING  */
    UNTIL = 1171,                  /* UNTIL  */
    UP = 1172,                     /* UP  */
    UPDATE = 1173,                 /* UPDATE  */
    UPDATERS = 1174,               /* UPDATERS  */
    UPON = 1175,                   /* UPON  */
    UPON_ARGUMENT_NUMBER = 1176,   /* "UPON ARGUMENT-NUMBER"  */
    UPON_COMMAND_LINE = 1177,      /* "UPON COMMAND-LINE"  */
    UPON_ENVIRONMENT_NAME = 1178,  /* "UPON ENVIRONMENT-NAME"  */
    UPON_ENVIRONMENT_VALUE = 1179, /* "UPON ENVIRONMENT-VALUE"  */
    UPPER = 1180,                  /* UPPER  */
    UPPER_CASE_FUNC = 1181,        /* "FUNCTION UPPER-CASE"  */
    USAGE = 1182,                  /* USAGE  */
    USE = 1183,                    /* USE  */
    USE_ALT = 1184,                /* "USE-ALT"  */
    USE_RETURN = 1185,             /* "USE-RETURN"  */
    USE_TAB = 1186,                /* "USE-TAB"  */
    USER = 1187,                   /* USER  */
    USER_DEFAULT = 1188,           /* "USER-DEFAULT"  */
    USER_FUNCTION_NAME = 1189,     /* "user function name"  */
    USING = 1190,                  /* USING  */
    UTF_8 = 1191,                  /* "UTF-8"  */
    UTF_16 = 1192,                 /* "UTF-16"  */
    V = 1193,                      /* V  */
    VALID = 1194,                  /* VALID  */
    VALIDATE = 1195,               /* VALIDATE  */
    VAL_STATUS = 1196,             /* "VAL-STATUS"  */
    VALIDATE_STATUS = 1197,        /* "VALIDATE-STATUS"  */
    VALIDATING = 1198,             /* VALIDATING  */
    VALUE = 1199,                  /* VALUE  */
    VALUE_FORMAT = 1200,           /* "VALUE-FORMAT"  */
    VALUES = 1201,                 /* VALUES  */
    VARIABLE = 1202,               /* VARIABLE  */
    VARIANT = 1203,                /* VARIANT  */
    VARYING = 1204,                /* VARYING  */
    VERTICAL = 1205,               /* VERTICAL  */
    VERY_HEAVY = 1206,             /* "VERY-HEAVY"  */
    VIRTUAL_WIDTH = 1207,          /* "VIRTUAL-WIDTH"  */
    VOLATILE = 1208,               /* VOLATILE  */
    VPADDING = 1209,               /* VPADDING  */
    VSCROLL = 1210,                /* VSCROLL  */
    VSCROLL_BAR = 1211,            /* "VSCROLL-BAR"  */
    VSCROLL_POS = 1212,            /* "VSCROLL-POS"  */
    VTOP = 1213,                   /* VTOP  */
    WAIT = 1214,                   /* WAIT  */
    WEB_BROWSER = 1215,            /* "WEB-BROWSER"  */
    WHEN = 1216,                   /* WHEN  */
    WHEN_COMPILED_FUNC = 1217,     /* "FUNCTION WHEN-COMPILED"  */
    WHEN_XML = 1218,               /* "WHEN"  */
    WIDTH = 1219,                  /* WIDTH  */
    WIDTH_IN_CELLS = 1220,         /* "WIDTH-IN-CELLS"  */
    WINAPI = 1221,                 /* WINAPI  */
    WINDOW = 1222,                 /* WINDOW  */
    WITH = 1223,                   /* WITH  */
    WORD = 1224,                   /* "Identifier"  */
    WORDS = 1225,                  /* WORDS  */
    WORKING_STORAGE = 1226,        /* "WORKING-STORAGE"  */
    WRAP = 1227,                   /* WRAP  */
    WRITE = 1228,                  /* WRITE  */
    WRITE_ONLY = 1229,             /* "WRITE-ONLY"  */
    WRITE_VERIFY = 1230,           /* "WRITE-VERIFY"  */
    WRITERS = 1231,                /* WRITERS  */
    X = 1232,                      /* X  */
    XML = 1233,                    /* XML  */
    XML_DECLARATION = 1234,        /* "XML-DECLARATION"  */
    XML_SCHEMA = 1235,             /* "XML-SCHEMA"  */
    Y = 1236,                      /* Y  */
    YYYYDDD = 1237,                /* YYYYDDD  */
    YYYYMMDD = 1238,               /* YYYYMMDD  */
    ZERO = 1239,                   /* ZERO  */
    LEVEL_NUMBER_IN_AREA_A = 1240, /* "level-number (Area A)"  */
    WORD_IN_AREA_A = 1241,         /* "Identifier (Area A)"  */
    SHIFT_PREFER = 1242            /* SHIFT_PREFER  */
  };
  typedef enum yytokentype yytoken_kind_t;
#endif

/* Value type.  */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef int YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif


extern YYSTYPE yylval;


int yyparse (void);


#endif /* !YY_YY_PARSER_TAB_H_INCLUDED  */
